# Generated by Django 4.1 on 2023-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_visibilidad_product_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='Enterprise Name')),
                ('location', models.TextField(verbose_name='Enterprise Google Maps Location')),
                ('email', models.EmailField(max_length=254, verbose_name='Enterprise Main Email')),
                ('tel', models.CharField(max_length=255, verbose_name='Enterprise Main Phone Number')),
                ('address', models.TextField(verbose_name='Enterprise Address')),
            ],
            options={
                'verbose_name': 'Enterprise Information',
                'verbose_name_plural': 'Enterprise Information',
            },
        ),
    ]
