# Generated by Django 4.1 on 2023-07-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enterprisedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAditionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact')),
                ('contact_aditional_info', models.CharField(blank=True, help_text='Optional', max_length=255, null=True, verbose_name='Contact Aditional Info')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enterprisedata')),
            ],
            options={
                'verbose_name': 'Enterprise Aditional Contact',
                'verbose_name_plural': 'Enterprise Aditional Contacts',
            },
        ),
    ]
