# Generated by Django 4.1 on 2023-07-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedata',
            name='facebook',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Enterprise Facebook Page'),
        ),
        migrations.AddField(
            model_name='enterprisedata',
            name='twitter',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Enterprise Twitter Page'),
        ),
        migrations.AddField(
            model_name='enterprisedata',
            name='youtube',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Enterprise Youtube Page'),
        ),
    ]
