# Generated by Django 4.2.3 on 2023-07-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enterprisedata_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedata',
            name='city',
            field=models.CharField(blank=True, help_text='Optional', max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='works/', verbose_name='Images'),
        ),
    ]
