# Generated by Django 4.2.3 on 2023-07-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enterprisedata_city_alter_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='En venta'),
        ),
    ]
