# Generated by Django 4.1 on 2023-07-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_is_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('content', models.TextField(verbose_name='Content')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('content', models.TextField(verbose_name='Content')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
            ],
            options={
                'verbose_name': 'Terms of Use',
                'verbose_name_plural': 'Terms of Use',
            },
        ),
    ]
