# Generated by Django 4.2.3 on 2023-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_commercialjoboffer_job_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedata',
            name='doc_folleto_digital',
            field=models.FileField(blank=True, null=True, upload_to='doc/', verbose_name='Folleto digital'),
        ),
        migrations.AddField(
            model_name='enterprisedata',
            name='doc_presentation',
            field=models.FileField(blank=True, null=True, upload_to='doc/', verbose_name='Carta de presentación'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(help_text='Poner imagen horizontal, relación aspecto 16:9 preferiblemente', upload_to='works/', verbose_name='Images'),
        ),
    ]
