# Generated by Django 4.2.3 on 2023-09-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_joboffer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialjoboffer',
            options={'ordering': ('is_checked', 'job_offer', '-pk'), 'verbose_name': 'Commercial Job Offer', 'verbose_name_plural': 'Commercial Job Offers'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ('is_active', '-pk'), 'verbose_name': 'Job Offer', 'verbose_name_plural': 'Job Offers'},
        ),
        migrations.AlterModelOptions(
            name='jobofferpool',
            options={'ordering': ('is_checked', 'job_offer', 'pk'), 'verbose_name': 'Job Offer Pool', 'verbose_name_plural': 'Job Offers Pools'},
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enterprise Main Phone Number'),
        ),
    ]
