# Generated by Django 4.2.3 on 2023-10-16 03:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contact_is_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialjoboffer',
            options={'ordering': ('is_checked', 'job_offer', '-pk'), 'verbose_name': 'Oferta de trabajo comercial', 'verbose_name_plural': 'Ofertas de trabajos comerciales'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseaditionalcontact',
            options={'verbose_name': 'Contacto adicional de la empresa', 'verbose_name_plural': 'Contactos adicionales de la empresa'},
        ),
        migrations.AlterModelOptions(
            name='enterprisedata',
            options={'verbose_name': 'Información de la empresa', 'verbose_name_plural': 'Informaciónes de la empresa'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ('is_active', '-pk'), 'verbose_name': 'Oferta de trabajo', 'verbose_name_plural': 'Ofertas de trabajos'},
        ),
        migrations.AlterModelOptions(
            name='jobofferpool',
            options={'ordering': ('is_checked', 'job_offer', 'pk'), 'verbose_name': 'Cantera de oferta de trabajo', 'verbose_name_plural': 'Canteras de ofertas de trabajos'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Política de privacidad', 'verbose_name_plural': 'Políticas de privacidad'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.AlterModelOptions(
            name='termsofuse',
            options={'verbose_name': 'Término de Uso', 'verbose_name_plural': 'Términos de Uso'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'verbose_name': 'Categoría de trabajos', 'verbose_name_plural': 'Categorías de trabajos'},
        ),
        migrations.AlterField(
            model_name='commercialjoboffer',
            name='business_offer',
            field=models.TextField(verbose_name='Oferta de negocio'),
        ),
        migrations.AlterField(
            model_name='commercialjoboffer',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Está revisada'),
        ),
        migrations.AlterField(
            model_name='commercialjoboffer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='commercialjoboffer',
            name='others',
            field=models.TextField(blank=True, null=True, verbose_name='Otros datos'),
        ),
        migrations.AlterField(
            model_name='commercialjoboffer',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de teléfomo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Está revisada'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='enterpriseaditionalcontact',
            name='contact',
            field=models.CharField(max_length=255, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='enterpriseaditionalcontact',
            name='contact_aditional_info',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, verbose_name='Info adicional'),
        ),
        migrations.AlterField(
            model_name='enterpriseaditionalcontact',
            name='contact_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('tel', 'Teléfono')], max_length=255, verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='address',
            field=models.TextField(verbose_name='Dirección de la empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='city',
            field=models.CharField(blank=True, help_text='Opcional', max_length=250, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo principal de la emresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='enterprise_name',
            field=models.CharField(max_length=255, verbose_name='Nombre de empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='facebook',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Página de Facebook de la empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='instagram',
            field=models.CharField(blank=True, help_text='Opcional', max_length=500, null=True, verbose_name='Página de instagram de la empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='location',
            field=models.TextField(verbose_name='Localizción de google maps de la Emppresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono principal de la empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='twitter',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Página de Twitter de la empresa'),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='youtube',
            field=models.CharField(blank=True, help_text='Optional', max_length=500, null=True, verbose_name='Página de Youtube de la empresa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=400, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Está Activo'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='formation',
            field=models.TextField(blank=True, null=True, verbose_name='Formación'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Está revisada'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='others',
            field=models.TextField(blank=True, null=True, verbose_name='Otros datos'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='habilidades'),
        ),
        migrations.AlterField(
            model_name='jobofferpool',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='effective_date',
            field=models.DateField(verbose_name='Fecha de Efectividad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.BooleanField(verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='effective_date',
            field=models.DateField(verbose_name='Fecha de Efectividad'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='version',
            field=models.CharField(max_length=255, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, help_text='Opcional', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(verbose_name='Testimonios'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.work', verbose_name='Trabajos'),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(help_text='Poner imagen horizontal, relación aspecto 16:9 preferiblemente', upload_to='works/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
