# Generated by Django 4.2.3 on 2023-10-17 03:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_commercialjoboffer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
