# Generated by Django 4.2.3 on 2023-10-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_privacypolicy_content_alter_termsofuse_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Cantidad de inventario'),
        ),
    ]
