# Generated by Django 4.2.3 on 2023-11-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_date_updated_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de inventario'),
        ),
    ]
