# Generated by Django 4.2.3 on 2023-11-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='link',
        ),
    ]
