# Generated by Django 4.2.3 on 2023-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_work_description_en_work_description_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Inglés'),
        ),
        migrations.AddField(
            model_name='work',
            name='name_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Portugués'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Descripción Inglés'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Descripción Portugués'),
        ),
    ]
