# Generated by Django 4.2.3 on 2023-12-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_work_description_en_work_description_pt_work_name_en_and_more'),
        ('core', '0027_remove_work_description_en_and_more'),
    ]

    operations = [
    ]
