# Generated by Django 4.2.3 on 2023-12-12 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20231212_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.AddField(
            model_name='enterprisedata',
            name='checkout_allowed',
            field=models.BooleanField(default=True, help_text='Permitir a los usuarios realizar compras', verbose_name='Permitir compras'),
        ),
        migrations.AddField(
            model_name='enterprisedata',
            name='tropipay_impuesto',
            field=models.FloatField(default=3.45, help_text='Porciento del total de la orden aumentado', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Impuesto de Tropipay'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Tiempo de entrega (días)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Precio')),
                ('delivery_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deliveryplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
