# Generated by Django 4.2.3 on 2023-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_deliveryplace_enterprisedata_checkout_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryplace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
