# Generated by Django 4.2.3 on 2023-12-13 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_deliveryplace_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('link_de_pago', models.CharField(blank=True, max_length=500, null=True)),
                ('total', models.FloatField(default=0, verbose_name='Importe total')),
                ('precio_envio', models.FloatField(default=0, verbose_name='Precio de envío')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Completada'), ('2', 'Pendiente'), ('3', 'Cancelada')], default='2', max_length=10, verbose_name='Estado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tiempo_de_entrega', models.PositiveIntegerField(verbose_name='Tiempo de entrega máximo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo del comprador')),
                ('detalles_direccion', models.TextField(blank=True, null=True, verbose_name='Detalles de dirección')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ('-date_created', '-status'),
            },
        ),
        migrations.AlterModelOptions(
            name='deliveryplace',
            options={'verbose_name': 'Lugar de entrega', 'verbose_name_plural': 'Lugares de entrega'},
        ),
        migrations.AlterModelOptions(
            name='deliveryprice',
            options={'verbose_name': 'Precio de entrega', 'verbose_name_plural': 'Precios de entrega'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ComponenteOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respaldo', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componente_orden', to='core.orden')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componente_producto', to='core.product')),
            ],
            options={
                'verbose_name': 'Componente de orden',
                'verbose_name_plural': 'Componentes de ordenes',
                'ordering': ('orden', 'producto'),
            },
        ),
    ]
