# Generated by Django 4.2.3 on 2023-12-13 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_orden_alter_deliveryplace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador único', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
