# Generated by Django 4.2.3 on 2023-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Identificador único', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
