# Generated by Django 4.2.3 on 2023-12-13 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
