# Generated by Django 4.2.3 on 2023-12-14 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, help_text='Identificador único', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
