# Generated by Django 4.2.3 on 2023-12-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprice',
            name='delivery_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deliveryplace', verbose_name='Lugar de entrega'),
        ),
        migrations.AlterField(
            model_name='deliveryprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto'),
        ),
    ]
