# Generated by Django 4.2.3 on 2023-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_orden_telefono_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='correo',
            field=models.CharField(max_length=250, verbose_name='Correo del comprador'),
        ),
    ]
