# Generated by Django 4.2.3 on 2023-12-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tropipay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tropipayconfig',
            name='tpp_url',
            field=models.CharField(blank=True, default='www.tropipay.com', max_length=255, null=True),
        ),
    ]
