# Generated by Django 4.1 on 2023-07-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='IndexSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Index',
            },
        ),
        migrations.CreateModel(
            name='ProductsPortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Products Portfolio',
                'verbose_name_plural': 'Products Portfolio',
            },
        ),
        migrations.CreateModel(
            name='SellProductsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Sell Products',
                'verbose_name_plural': 'Sell Products',
            },
        ),
        migrations.CreateModel(
            name='WorksPortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Works Portfolio',
                'verbose_name_plural': 'Works Portfolio',
            },
        ),
        migrations.CreateModel(
            name='WorkWithUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Work With Us',
                'verbose_name_plural': 'Work With Us',
            },
        ),
    ]
