# Generated by Django 4.1 on 2023-07-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSectionPerks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional', max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, help_text='Optional', null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, help_text='Optional', null=True, upload_to='sections/about us/', verbose_name='Image')),
                ('about_us_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.aboutussection')),
            ],
            options={
                'verbose_name': 'About Us Section Perk',
                'verbose_name_plural': 'About Us Section Perks',
            },
        ),
    ]
