# Generated by Django 4.2.3 on 2023-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_aboutussectionperks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtitle'),
        ),
    ]
