# Generated by Django 4.2.3 on 2023-10-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_aboutussection_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutussection',
            options={'verbose_name': 'Sobre nosotros', 'verbose_name_plural': 'Sobre nosotros'},
        ),
        migrations.AlterModelOptions(
            name='contactussection',
            options={'verbose_name': 'Contáctenos ', 'verbose_name_plural': 'Contáctenos'},
        ),
        migrations.AlterModelOptions(
            name='productsportfoliosection',
            options={'verbose_name': 'Productos del portafolio', 'verbose_name_plural': 'Productos del portafolio'},
        ),
        migrations.AlterModelOptions(
            name='sellproductssection',
            options={'verbose_name': 'Producto de venta', 'verbose_name_plural': 'Productos en venta'},
        ),
        migrations.AlterModelOptions(
            name='worksportfoliosection',
            options={'verbose_name': 'Portafolio de trabajo', 'verbose_name_plural': 'Portafolios de trabajos'},
        ),
        migrations.AlterModelOptions(
            name='workwithussection',
            options={'verbose_name': 'Trabaja con nosotros', 'verbose_name_plural': 'Trabaja con nosotros'},
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='aboutussectionperks',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional', null=True, upload_to='sections/about us/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='aboutussectionperks',
            name='text',
            field=models.TextField(blank=True, help_text='Opcional', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='aboutussectionperks',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='subtitle',
            field=models.TextField(verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
