# Generated by Django 4.2.3 on 2023-10-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_aboutussection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndPrivacyPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='sections/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Términos de Uso y Política de Privacidad',
                'verbose_name_plural': 'Términos de Uso y Política de Privacidad',
            },
        ),
    ]
