# Generated by Django 4.2.3 on 2023-11-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_tropipayconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutussection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='aboutussection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='aboutussection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='aboutussection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='contactussection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='contactussection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='contactussection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='contactussection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='indexsection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='indexsection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='indexsection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='indexsection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='productsportfoliosection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='productsportfoliosection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='productsportfoliosection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='productsportfoliosection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='sellproductssection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='sellproductssection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='sellproductssection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='sellproductssection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='termsandprivacypolice',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='termsandprivacypolice',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='termsandprivacypolice',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='termsandprivacypolice',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='worksportfoliosection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='worksportfoliosection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='worksportfoliosection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='worksportfoliosection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
        migrations.AddField(
            model_name='workwithussection',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AddField(
            model_name='workwithussection',
            name='subtitle_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AddField(
            model_name='workwithussection',
            name='title_en',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Inglés'),
        ),
        migrations.AddField(
            model_name='workwithussection',
            name='title_pt',
            field=models.CharField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', max_length=255, null=True, verbose_name='Título Portugués'),
        ),
    ]
