# Generated by Django 4.2.3 on 2023-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_aboutussection_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutussection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='aboutussection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='contactussection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='indexsection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='productsportfoliosection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='sellproductssection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='termsandprivacypolice',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='termsandprivacypolice',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='worksportfoliosection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Sutítulo Inglés'),
        ),
        migrations.AlterField(
            model_name='workwithussection',
            name='subtitle_pt',
            field=models.TextField(blank=True, help_text='Dejar este campo vacío hará que el sistema proponga una traducción automática. La traducción automática puede ser modificada.', null=True, verbose_name='Subtítulo Portugués'),
        ),
    ]
