# Generated by Django 4.2.3 on 2023-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_alter_aboutussection_subtitle_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TropipayConfig',
        ),
    ]
